mgmt-hub/README.md, mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/docker-compose.yml
- now works on macOS
- added `-S` and `-s` to temporarily stop the services and then restart them
- enhance `-P` (purge) to also uninstall deb pkgs
=> Mac support

mgmt-hub/README.md, mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/docker-compose.yml, mgmt-hub/test-sdo.sh
=> added sdo as 1 of the mgmt hub components deployed

mgmt-hub/README.md, mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/test-sdo.sh
=> updated for new SDO-support changes, and added some error checking

mgmt-hub/deploy-mgmt-hub.sh
=> update the horizon agent pkg names, and tweak the output at the end

mgmt-hub/deploy-mgmt-hub.sh
=> increased timeout wait for exchange and agent

mgmt-hub/deploy-mgmt-hub.sh
=> fixed pkg tar file names

mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/test-sdo.sh
=> updates for recent versions and add -u flag

mgmt-hub/deploy-mgmt-hub.sh
Added command to delete openhorizon images
=> Openhorizon image remove

mgmt-hub/README.md, mgmt-hub/deploy-mgmt-hub.sh
=> Issue 49: Add agent-install.cfg to all-in-1 CSS

mgmt-hub/README.md, mgmt-hub/deploy-mgmt-hub.sh
=> Issue 55: Add an option to not install the edge node for all-in-one

mgmt-hub/test-sdo.sh
=> add ubuntu 20 support to test-sdo.sh

mgmt-hub/deploy-mgmt-hub.sh
Signed-off-by: Yuri Pravosud <yuri.pravosud2@ibm.com>
Resolve #58 
Need to improve Horizon packages installation logics in RHEL on ppc64le platform avoiding packages deletion. Such deletion potentially could affect already running hzn services and/or Docker containers that have Horizon packages dependency. Also need to restrict support of RHEL to 8.x versions only as a mainstream in Open Horizon now.
=> Issue #58 Improve support ppc64le platform in RHEL

mgmt-hub/deploy-mgmt-hub.sh
=> Issue 62: AGBOT_ID is not honored in deploy-mgmt-hub.sh

mgmt-hub/README.md, mgmt-hub/agbot-tmpl.json, mgmt-hub/css-tmpl.conf, mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/docker-compose-agbot2.yml, mgmt-hub/docker-compose.yml
See https://github.com/open-horizon/devops/issues/64 for details.
=> Issue 64: All-in-1 improvements for e2edev

mgmt-hub/agbot-tmpl.json
=> Issue 64: fix agbot APIListen config value

mgmt-hub/deploy-mgmt-hub.sh
=> Issue 11: fix case when OH_DONT_DOWNLOAD is empyt

mgmt-hub/README.md, mgmt-hub/deploy-mgmt-hub.sh
=> Issue 11 continuation: support edge node for all-in-1 https mgmt hub

mgmt-hub/deploy-mgmt-hub.sh
=> Issue 76: Default of DOCKER_COMPOSE_CMD should be golang version

mgmt-hub/deploy-mgmt-hub.sh
=> Add default for SDO_GET_CFG_FILE_FROM

mgmt-hub/deploy-mgmt-hub.sh
=> fixed typo in crt name

mgmt-hub/deploy-mgmt-hub.sh
Signed-off-by: Eli Latocki <eli.latocki@ibm.com>
=> Issue 87 - Unresolved filename in deploy-mgmt-hub.sh

mgmt-hub/README.md
This is a quick PR to force the new GitHub action to kick off and copy these docs over to the Documentation repo.
I fixed some small markdown Linter warnings
Signed-off-by: John Walicki <johnwalicki@gmail.com>
=> Lint fixes

.github/workflows/copy-docs.yml
Signed-off-by: John Walicki <walicki@us.ibm.com>
See #120  #121 
The wrong readme.md was copied over to the OH Docs repo.
=> copy mgmt-hub/docs/readme.md

docs/index.md
Signed-off-by: John Walicki <walicki@us.ibm.com>
=> Issue 120: Fix Anchor Tags

docs/index.md
Signed-off-by: Marhababanu Chariwala <marhabac33@gmail.com>
fixes https://github.com/open-horizon/devops/issues/130
=> Issue 130 - fixed hyperlink format

README.md, mgmt-hub/README.md
Signed-off-by: Marhababanu Chariwala <marhabac33@gmail.com>
=> Issue 128 - fixed broken link in README

mgmt-hub/deploy-mgmt-hub.sh
Signed-off-by: John Walicki <johnwalicki@gmail.com>
Fixes #133
This fix adds support for Ubuntu 22.x
=> Issue #133 : Ubuntu 22.x support

CHANGELOG.md, mgmt-hub/bao-tmpl.json, mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/docker-compose.yml
References: #167
Changes:
- Changes Vault references to OpenBao.
=> Issue-167: Changes Vault references to OpenBao.

mgmt-hub/bao-tmpl.json, mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/docker-compose.yml
References: #167
Changes:
- Reverted some of the reference changes.
=> Issue 167: Reverted some of the reference changes.

mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/docker-compose.yml
References:
Changes:
- Adding support for Exchange v2.124.0+ configuration.
=> Adding support for Exchange v2.124.0+ configuration.

CHANGELOG.md, mgmt-hub/agbot-tmpl.json, mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/docker-compose.yml
References:
Changes:
- Removed auth method trust from PostgreSQL containers.
- Added user passwords to PostgreSQL containers.
- Added scram_sha_256 cryptographic hashing to PostgreSQL containers for user passwords.
=> Hardening PostgreSQL containers.

CHANGELOG.md, mgmt-hub/agbot-tmpl.json, mgmt-hub/deploy-mgmt-hub.sh, mgmt-hub/docker-compose.yml
=> pstream Merge

mgmt-hub/deploy-mgmt-hub.sh
References: #193 #196
Changes:
- Issue 196: Fixes OpenBao plugin location.
=> Issue 196: Fixed OpenBao plugin location.

mgmt-hub/deploy-mgmt-hub.sh
References: #200
Changes:
- Issue 200: Fixed typo in truststore file path.
=> Issue 200: Fixed typo in truststore file path.

docs/index.md
Signed-off-by: Joe Pearson <joe.pearson@us.ibm.com>
=> Issue 203: Add section on removing all-in-one

docs/index.md
Update front matter in documentation files to use the correct copyright statement, update lastupdated dates, and update years fields.
=> Issue 205: Update front matter in documentation files

CHANGELOG.md, mgmt-hub/deploy-mgmt-hub.sh
References:
Changes:
- Compose alias is saved to bash_aliases to survive reboot.
=> Compose alias is saved to bash_aliases to survive reboot.
